### ISSUE TITLE
Support for Elasticsearch v6.x+

### ISSUE THREAD

**Issue by Lngramos** [phillbaker/terraform-provider-elasticsearch#10]
Hey @phillbaker,

I'm targeting an Elasticsearch cluster which is on version 6.x, but I'm having issues due to breaking API changes from v5 to v6. This is understandable given this provider is using the v5 release branch github.com/olivere/elastic.

To fix my issue in the short term, I've created a private fork that is now upgraded to use the v6 client.

But ideally, I wouldn't want to rely on my workaround and instead I would like to see a way to use your provider despite of the target ES version. Have you put any though in allowing this provider handle different versions of Elasticsearch?

Alternatively, we could perhaps confirm if the v6 API/client is backwards compatible with the v5 Index Template, Snapshot Repository and Kibana Object APIs that this provider currently uses. If so, consider upgrading to the client to v6. Though this doesn't solve the problem at hand in the long term.

**Comment by phillbaker** [comment]
@Lngramos sorry for the slow reply. Good question!

Short answer is that I haven't thought it through, however, I'd definitely be interested in supporting v6. I will take a look at your changes](https://github.com/Lngramos/terraform-provider-elasticsearch/commit/4ac83387e16d6d22010eec83ad175f6fe7d8dfb0) and propose something - taking a quick look [at the breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-6.0.html) and your own experience seems to indicate that the changes are significant.

My thoughts on options are:
1. mirror the underlying compatibility approach of [olivere/elastic](https://github.com/olivere/elastic#releases) by maintaining release branches in this repo
1. add a build flag to determine which version of the dependency to build the client against
1. something else?

Since terraform supports versioning providers and the upstream library follows release branches, I'm leaning toward (1). Happy to hear your thoughts and any other options.

**Comment by phillbaker** [comment]
Getting closer to a resolution here. I'm leaning to (3) above, similar to https://github.com/Yelp/elastalert/pull/1472, supporting both versions based on detection.

**Comment by phillbaker** [comment]
I've pushed work on this to the branch `support-es-6`, however, there's one failing test for the index templates code.

I've opened https://github.com/olivere/elastic/issues/868 to help clarify some of the workings of the upstream elasticsearch library.

**Comment by phillbaker** [comment]
@Lngramos if you'd like to try out master, ESv6 should be working!
