### ISSUE TITLE
Google 'grpc/naming' not found when installing with 'go get'

### ISSUE THREAD

**Issue by tdmalone** [phillbaker/terraform-provider-elasticsearch#185]
I've been installing this provider in CI for awhile with `go get`, and yesterday it started failing with:
```
$ go get github.com/phillbaker/terraform-provider-elasticsearch@master
github.com/phillbaker/terraform-provider-elasticsearch imports
        github.com/hashicorp/terraform-plugin-sdk/plugin imports
        github.com/hashicorp/terraform-plugin-sdk/internal/plugin/discovery imports
        github.com/hashicorp/go-getter imports
        cloud.google.com/go/storage imports
        google.golang.org/api/option imports
        google.golang.org/api/internal imports
        google.golang.org/grpc/naming: cannot find module providing package google.golang.org/grpc/naming
```

I'm very light on Go knowledge but looking at that failing package at https://pkg.go.dev/google.golang.org/grpc/naming, it appears that:
- ‘this package is not in the latest version of its module’ (according to the tooltip on Latest)
- the package is deprecated; the readme says to 'please use package resolver instead'

I'm not sure if this is an issue in this provider or if it's upstream, but is there anything I can do to fix this on my end?

Potentially relevant information:
```
$ go version
go version go1.16.2 darwin/amd64

$ echo $GOPATH
/Users/tim/go

$ echo $GO111MODULE
on
```

I also tried using `go install` instead of `go get`:
```
$ go install github.com/phillbaker/terraform-provider-elasticsearch@master
go install github.com/phillbaker/terraform-provider-elasticsearch@master: github.com/phillbaker/terraform-provider-elasticsearch@v1.5.8-0.20210620202447-4b2314a8d353
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by tdmalone** [comment]
Hmm might be related to https://github.com/grpc/grpc-go/issues/3726? (But I'm not a Go programmer so am out of my depth here 😬 )

**Comment by phillbaker** [comment]
Ah, sorry to hear that this broke things. This is due to https://github.com/phillbaker/terraform-provider-elasticsearch/commit/7a6207d50a60a55bcc9d1b653599311b5dfd529f which included the use of a `replace` directive in `go.mod` to workaround the same missing import issue. Unfortunately a transitive dependency in upgrading the `elastic` library introduced this issue.

I think you should also be able to `go get google.golang.org/grpc@v1.29.1` to mimic what `replace` is doing, see https://github.com/DataDog/dd-trace-go/pull/688.

Based on https://github.com/open-telemetry/opentelemetry-collector/issues/1366#issuecomment-658899511, I think I should be able to add an indirect dependency on the api package, I've tried that in https://github.com/phillbaker/terraform-provider-elasticsearch/commit/75a94426e645be9622ac25af8b7c489bdbd2b1c1, i'll just need to get cleaned up to pass CI.

**Comment by phillbaker** [comment]
Merged this to master, and a `go get github.com/phillbaker/terraform-provider-elasticsearch` works for me, hows it look for you @tdmalone ?

**Comment by tdmalone** [comment]
Thanks so much for the quick resolution @phillbaker. Our CI just passed so it's working for us now too!
