### ISSUE TITLE
Error: Missing required argument while trying to deploy resource "elasticsearch_opendistro_role"

### ISSUE THREAD

**Issue by niladriforu** [phillbaker/terraform-provider-elasticsearch#269]
Error message is : The argument "url" is required, but was not set.

**Comment by phillbaker** [comment]
Hello, can you please include the following:
* terraform version
* provider version
* elasticsearch version (and opendistro version if relevant)
* redacted version of the terraform resource configuration
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

**Comment by phillbaker** [comment]
Hi @niladriforu without further information, this issue isn't possible to investigate. I'm going to close this issue for now, please reopen it if further information can be provided.

**Comment by lucianpatian** [comment]
it's the first time i'm using the provider and i got the same error. turns out that i was missing the url parameter from the providers.tf

i'm leaving this comment in case other noobs get stuck in the future :)

terraform {
  required_providers {
    elasticsearch = {
      source = "phillbaker/elasticsearch"
      version = "2.0.4"
    }
  }
}

provider "elasticsearch" {
  url = "https://${aws_opensearch_domain.osdomain.endpoint}"
  sign_aws_requests = true
}
