### ISSUE TITLE
Error: elastic: Error 403 (Forbidden)

### ISSUE THREAD

**Issue by grglzrv** [phillbaker/terraform-provider-elasticsearch#297]
Hello,

I am getting 403 (Forbidden) 

```
01:32:13  + terraform apply '-lock-timeout=10m' plan
01:32:16  elasticsearch_opensearch_role.this: Creating...
01:32:16  elasticsearch_opensearch_user.this: Creating...
01:32:17  ╷
01:32:17  │ Error: elastic: Error 403 (Forbidden)
01:32:17  │ 
01:32:17  │   with elasticsearch_opensearch_role.this,
01:32:17  │   on main.tf line 162, in resource "elasticsearch_opensearch_role" "this":
01:32:17  │  162: resource "elasticsearch_opensearch_role" "this" {
```

terraform version - v1.2.4
registry.terraform.io/phillbaker/elasticsearch v2.0.2
AWS OpenSearch - Elasticsearch 7.9 / 7.10
master user is enabled 

terraform code:

```
providers.tf

provider "elasticsearch" {
  url               = "https://${var.es_host}"
  aws_access_key = "XXXXX"
  aws_secret_key =  "XXXXX"
  sign_aws_requests = true
}

main.tf

resource "elasticsearch_opensearch_role" "this" {
  role_name = var.name

  cluster_permissions = [
    "cluster_monitor",
    "indices_all",
  ]

  index_permissions {
    index_patterns  = ["${var.name}-*"]
    allowed_actions = ["indices_all"]
  }

  index_permissions {
    index_patterns = ["*"]
    allowed_actions = [
      "indices:admin/aliases/get",
      "indices:admin/rollover",
      "indices_monitor",
    ]
  }
}

resource "elasticsearch_opensearch_roles_mapping" "this" {
  role_name = elasticsearch_opensearch_role.this.id
  users     = [elasticsearch_opensearch_user.this.id]
}

resource "elasticsearch_opensearch_user" "this" {
  username = var.name
  password = random_password.es.result
}
```

**Comment by grglzrv** [comment]
I've raised new AWS OpenSearch, but now I got 400 (Bad Request), with the same versions
 
 terraform version - v1.2.4
registry.terraform.io/phillbaker/elasticsearch v2.0.2
AWS OpenSearch - Elasticsearch 7.9
Elasticsearch with Cognito auth 
 
 ```
lan: 4 to add, 0 to change, 0 to destroy.
elasticsearch_opensearch_user.this: Creating...
elasticsearch_opensearch_role.this: Creating...
╷
│ Error: elastic: Error 400 (Bad Request)
│ 
│   with elasticsearch_opensearch_role.this,
│   on main.tf line 162, in resource "elasticsearch_opensearch_role" "this":
│  162: resource "elasticsearch_opensearch_role" "this" {
│ 
╵
╷
│ Error: elastic: Error 400 (Bad Request)
│ 
│   with elasticsearch_opensearch_user.this,
│   on main.tf line 190, in resource "elasticsearch_opensearch_user" "this":
│  190: resource "elasticsearch_opensearch_user" "this" {
│ 
╵
Releasing state lock. This may take a few moments...
 ```

**Comment by grglzrv** [comment]
Error: elastic: Error 400 (Bad Request) with AWS OpenSearch - Elasticsearch 7.10 version BUT  without Cognito and master user

**Comment by phillbaker** [comment]
Hello, what steps have you taken so far to debug the issue? Does this happen for all resources or just roles? A 403 indicates a permission denied, so please check the your configuration and AWS documentation for what resources the user is allowed to access. You can also search this repository for similar issues in the past: https://github.com/phillbaker/terraform-provider-elasticsearch/issues?q=is%3Aissue+403

Please include the following information:
* from where are you running the provider?
* where is the elasticsearch cluster located?
* what is the networking configuration for where the elasticsearch cluster runs and all the networks connecting the location where the provider is running to the cluster?


Note: Issues on this repository are for reporting bugs and feature requests for this provider, not providing support for unique environments. In order to investigate this, a reproducible case may needs to be provided, if that can't be provided, we'll have to close this issue to focus on widely impacting issues.

**Comment by grglzrv** [comment]
I've solved the issue by adding the master user & password into elasticsearch provider, thanks for your reply.
