### ISSUE TITLE
Support authetication via APIKEY

### ISSUE THREAD

**Issue by nelg** [phillbaker/terraform-provider-elasticsearch#56]
It would be nice to able to authenticate to Elasticsearch using an API key.

It looks like the underlying go library supports it.
https://github.com/elastic/go-elasticsearch/blob/86a626c2a3459a406cce4aab02f802b87d5660a8/elasticsearch.go#L38

**Comment by phillbaker** [comment]
> It looks like the underlying go library supports it.

This provider currently uses github.com/olivere/elastic, seems similar to https://github.com/olivere/elastic/issues/1131#issuecomment-508213098

**Comment by phillbaker** [comment]
Using curl this is done as `-H "Authorization: ApiKey $ECE_API_KEY"`, see https://www.elastic.co/guide/en/cloud-enterprise/current/ece-api-command-line.html

**Comment by phillbaker** [comment]
@nelg what elasticsearch provider are you using that requires authorization via APIKEY?

If you're running on elastic cloud, the provider here: https://github.com/elastic/terraform-provider-ec, can be used to manage configuration within elastic cloud (authentication using APIKEY) -similar to the AWS provider being used to manage clusters created by AWS' service. The two providers should be complementary. The generated user/password by elastic cloud is used to access the cluster itself using this provider with basic auth, please see the docs.

If that doesn't work, please let me know, or otherwise clarify the intent of this issue.

**Comment by nelg** [comment]
@phillbaker  - The reason to use APIKEY, would be so that when we are using the terraform-provider-elasticsearch we can authenticate to Elasticsearch without having to have a username/password setup for Terraform. 

This is different from the elastic cloud provider (which we don't need at present).

It would change the workflow from having a dedicated terraform user in Elasticsearch, to being able to login to Elasticsearch as oneself (uses AD to login).  Then can generate an APIKEY with an expiry, following: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html

It generally is better from an auditing/security point of view, and to allow multiple different people to work on the same project without having to each have their own dedicated user created in Elasticsearch to run terraform with.    They can't use their AD creds directly because AD auth is via SAML.

Happy to response if you this is not clear

**Comment by nelg** [comment]
Thank you @phillbaker  - I will switch to using this method of auth.
